name: bitcoin_bip44
version: 0.1.2
description: Library implementing Bitcoins BIP44 (HD wallet organization) specification in a Flutter friendly fashion.
homepage: https://github.com/inapay/bitcoin_bip32

dependencies:
    bitcoin_bip32: ^0.1.1
    bech32: ^0.1.2
    http: ^0.12.0
    pointycastle: ^1.0.2

dev_dependencies:
    test: ^1.14.2
    hex: ^0.1.2
    mock_web_server:
        git: https://github.com/haarts/MockWebServer.git

environment:
    sdk: ">=2.4.0 <3.0.0"
