name: bitcoin_bip44
version: 0.1.1
description: Library implementing Bitcoins BIP44 (HD wallet organization) specification in a Flutter friendly fashion.
author: Kolibri POS authors <info@kolibripos.com>
homepage: https://github.com/Kolibri-POS/bitcoin_bip32

dependencies:
    bitcoin_bip32: ^0.1.0
    bech32: ^0.1.0
    http: ^0.12.0
    pointycastle: ^1.0.0-rc4

dev_dependencies:
    test: ^1.3.4
    hex: ^0.1.2
    mock_web_server:
        git: https://gitlab.com/haarts/MockWebServer.git
        version: ^2.1.0


environment:
    sdk: ">=2.0.0 <3.0.0"
