name: bitcoin_bip44
version: 0.1.0
description: Library implementing Bitcoins BIP44 (HD wallet organization) specification in a Flutter friendly fashion.
author: Kolibri POS authors <info@kolibripos.com>
homepage: https://github.com/Kolibri-POS/bitcoin_bip32

dependencies:
    bitcoin_bip32: 0.1.0

dev_dependencies:
    test: ^1.3.4

environment:
    sdk: ">=2.0.0 <3.0.0"
